# Generated by Django 4.1 on 2022-08-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
