# Generated by Django 4.1 on 2022-08-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_alter_court_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=50),
            preserve_default=False,
        ),
    ]
